
delta:
  seller_name: "Delta Ferreteria Industrial"
  tabla_crudos: "delta_registros_precios"
  tabla_kpis: "delta_kpis_diarios"
  urls:
  - "https://www.mercadolibre.com.ar/4-ruedas-para-muebles-giratorias-50mm-rueditas-2-con-freno/p/MLA47101189"
  - "https://www.mercadolibre.com.ar/tornillos-autoperforantes-madera-6-x-1-1436x32mmx1000u/p/MLA27039273"
  - "https://www.mercadolibre.com.ar/4-ruedas-para-andamios-tubulares-c-freno-chapa-y-goma-160mm/p/MLA45889843"
  - "https://www.mercadolibre.com.ar/tornillo-autoperforante-techo-14-x-2-bolsa-x-100-un-gramabi-con-arandela-chapa-goma-vulcanizada-punta-mecha-metal-madera/p/MLA36702822"
  - "https://www.mercadolibre.com.ar/taco-tarugo-universal-fischer-sx10-para-ladrillo-hueco-balde-por-400-unidades-fischer-codigo-616286/p/MLA27703346"
  - "https://www.mercadolibre.com.ar/autoperforante-punta-aguja-tornillo-14-x-2-12-bremen-100-u/p/MLA27980273"
  - "https://www.mercadolibre.com.ar/alambre-soldar-mig-flux-sin-gas-08mm-1kg-lusqtoff-lqflux081/p/MLA23521792"
  - "https://www.mercadolibre.com.ar/sellador-acrilico-premium-fischer-310ml-pintable-y-resistente-para-intemperie-ideal-para-sellado-de-grietas-juntas-en-interior-y-exterior-compatible-con-pintura-alta-adherencia-y-durabilidad/p/MLA25921061"
  - "https://www.mercadolibre.com.ar/tornillo-drywall-madera-negro-6-x-1-12-x500-unidades/p/MLA28891467"
  - "https://www.mercadolibre.com.ar/taco-tarugo-universal-sx6-para-ladrillo-hueco-balde-por-1800-unidades-fischer-codigo-616283/p/MLA27467212"
  - "https://www.mercadolibre.com.ar/taco-tarugo-universal-fischer-sx6-para-ladrillo-hueco-caja-por-100-unidades-fischer-codigo-608906/p/MLA28296692"
  - "https://www.mercadolibre.com.ar/fischer-ms-pega-sella-rellena-express-sellador-cartucho-color-gris/p/MLA34133018"
  - "https://www.mercadolibre.com.ar/alambre-mig-mig-soldar-09mm-rollo-5kg-lusqtoff-lqal-095-color-cobre/p/MLA44475243"
  - "https://www.mercadolibre.com.ar/taco-tarugo-universal-fischer-sx8-para-ladrillo-hueco-caja-por-100-unidades-fischer-codigo-608908/p/MLA28569984"
  - "https://www.mercadolibre.com.ar/tornillo-autoperforante-t1-punta-mecha-8x34-x-500-unidades/p/MLA27293955"
  - "https://www.mercadolibre.com.ar/alambre-soldar-mig-sin-gas-flux-08mm-5kg-lusqtoff-3-cts/p/MLA44532080"
  - "https://www.mercadolibre.com.ar/alambre-soldar-mig-mag-flux-09mm-sin-gas-rollo-1kg-lusqtoff/p/MLA44521909"
  - "https://www.mercadolibre.com.ar/tornillo-para-madera-autoperforante-8x2-negro-x-1000-u/p/MLA29394237"
  - "https://www.mercadolibre.com.ar/tornillo-drywal-madera-pta-aguja-6-x-34-paso-grueso-1000u/p/MLA24434328"
  - "https://www.mercadolibre.com.ar/dorado-para-hormigon-75-x-72mm-tornillo-torx-x-100-unidades/p/MLA45551014"
  - "https://www.mercadolibre.com.ar/desmalezadora-lusqtoff-ld52-7-52cc-17hp/p/MLA19048476"
  - "https://www.mercadolibre.com.ar/bomba-presurizadora-013-hp-100-w-lusqtoff-lps15-85z-altura-max-85-m/p/MLA19693451"
  - "https://www.mercadolibre.com.ar/termofusora-800w-maquina-termofusion-6-boquillas-lusqtoff/p/MLA26364114"
  - "https://www.mercadolibre.com.ar/sierra-circular-electrica-disco-lusqtoff-csl1500-8-185mm-1500watts-50hz-5500-rpm/p/MLA16048201"
  - "https://www.mercadolibre.com.ar/electrosierra-a-bateria-lusqtoff-cargador-color-naranja/p/MLA37011151"
  - "https://www.mercadolibre.com.ar/sierra-cortadora-sensitiva-lusqtoff-14-2000w-maquina-corte-cm-14k/p/MLA27112962"
  - "https://www.mercadolibre.com.ar/electrosierra-motosierra-lusqtoff-2000w-espada-40cm-esl200-8-color-anaranjado/p/MLA19590559"
  - "https://www.mercadolibre.com.ar/juego-herramientas-lusqtoff-150pzs-racing-caja-set-tubos-color-naranja/p/MLA33317217"
  - "https://www.mercadolibre.com.ar/sopladora-aspiradora-trituradora-lusqtoff-hojas-pasto-2400w-spl2400-8/p/MLA19590553"
  - "https://www.mercadolibre.com.ar/motobomba-industrial-nafta-65-hp-dogo-agua-600-lmin-28-mts/p/MLA21851053"
  - "https://www.mercadolibre.com.ar/lusqtoff-hidrolavadora-hl-120-1200w-7mpa-de-presion-50hz/p/MLA13121234"
  - "https://www.mercadolibre.com.ar/cortacerco-51-cm-550-watts-lusqtoff-funda-cuchilla-col550-8/p/MLA22575986"
  - "https://www.mercadolibre.com.ar/clavadora-neumatica-15-a-50-mm-bremen-7264/p/MLA24748709"
  - "https://www.mercadolibre.com.ar/engrampadora-neumatica-calibre-ga21-bremen-ideal-tapiceria/p/MLA26919382"
  - "https://www.mercadolibre.com.ar/desmalezadora-niwa-dnw-52-a-explosion-2-tiempos-52cc/p/MLA17445014"
  - "https://www.mercadolibre.com.ar/cortadora-plasma-inverter-corte-10mm-lusqtoff-incut-40/p/MLA26502835"
  - "https://www.mercadolibre.com.ar/cortadora-de-baldosas-rubi-star-63-con-maleta/p/MLA13391633"
  - "https://www.mercadolibre.com.ar/compresor-de-aire-electrico-portatil-lusqtoff-lc-2025bk-25l-2hp-manguera-1-pistolas-naranja/p/MLA19464914"
  - "https://www.mercadolibre.com.ar/llave-de-impacto-composite-en-kit-encastre-12-bremen-11-piezas/p/MLA28503629"
  - "https://www.mercadolibre.com.ar/engrampadora-triple-con-maletin-bremen-1000-grampas-500-clavos/p/MLA23891564"
  - "https://www.mercadolibre.com.ar/batidor-mezclador-pintura-sds-plus-600x120-7789-bremen/p/MLA27258127"
  - "https://www.mercadolibre.com.ar/pelacables-automatico-frontal-205-mm-bremen/p/MLA24151844"
  - "https://www.mercadolibre.com.ar/amoladora-recta-neumatica-bremen-kit-16-pz-matriceria-torno/p/MLA53290110"



# dinamo:
#   seller_name: "DINAMO MATERIALES ELECTRICOS"
#   tabla_crudos: "dinamo_registros_precios"
#   tabla_kpis: "dinamo_kpis_diarios"
#   urls:
#   - "https://www.mercadolibre.com.ar/curva-1-pulgada-cano-pvc-rigido-25mm-diametro-genrod-pack-10/p/MLA24704266"
#   - "https://www.mercadolibre.com.ar/aplique-exterior-led-macroled-aecn-x1-cuadrado-unidirec-gu10/p/MLA35840495"
#   - "https://www.mercadolibre.com.ar/cano-corrugado-34-genrod-losa-semipesado-gris-25m-ignifugo/p/MLA36023599"
#   - "https://www.mercadolibre.com.ar/spot-embutir-redondo-fijo-antideslumbrante-aluminio-led-color-blanco-cromo-macroled/p/MLA20726801"
#   - "https://www.mercadolibre.com.ar/lampara-tubo-calida-filamento-2w-vidrio-ambar-2200k-color-de-la-luz-blanco-calido/p/MLA21466856"
#   - "https://www.mercadolibre.com.ar/panel-plafon-led-12w-aplicar-redondo-negro-macroled-estructura-negro-calido/p/MLA19775380"
#   - "https://www.mercadolibre.com.ar/gabinete-estanco-genrod-s9000-ccontrafrente-450x450x100mm/p/MLA23933504"
#   - "https://www.mercadolibre.com.ar/conector-para-cano-rigidocorrugado-1pulgada-25mm-x50-genrod/p/MLA26917123"
#   - "https://www.mercadolibre.com.ar/union-cano-rigidocorrugado-genrod-78-22mm-pvc-x10/p/MLA25710674"
#   - "https://www.mercadolibre.com.ar/union-acople-cano-rigido-1-pulgada-pvc-25mm-electricidad-x10/p/MLA29726299"
#   - "https://www.mercadolibre.com.ar/curva-de-pvc-genrod-para-cano-rigido-22-mm-78-x-10-unidades/p/MLA26539509"